### PR TITLE
US41549: OTEL - Metal Telemetry Service - Add "Telemetry" network purpose

### PR DESCRIPTION
**Pull request by patricia-dibenedetto**
Add "Telemetry" network purpose

1 file to be reviewed: v1/api/swagger/components/schemas/NetworkPurpose.yaml
other files are auto generated

### CODE REVIEW

**Review by chaitra-mylarappachar — APPROVED** [review]
LGTM.
Recently LHO team reported trouble when new states were added, so tagging @neilgierman..

**Review by neilgierman — APPROVED** [review]

**Comment by patricia-dibenedetto** [comment]
fyi, Redocly link checker errors are not related to this PR and I'm unable to get response in slack #glcp-doc-portal channel.

**Comment by chaitra-mylarappachar** [comment]
> > LGTM. Recently LHO team reported trouble when new states were added, so tagging @neilgierman..
> 
> We need to coordinate this release with a quake release. There is a list of steps in the wiki on how to bring a project api change all the way through the products.

Is this the right wiki https://github.com/hpe-hcss/quake/wiki/Release-and-Development-Flow ? I think, this particular change can be released, there won't be any side effects even if the server side is still old. Again, Phil's TF changes require a new metal client release.

**Comment by chaitra-mylarappachar** [comment]
> fyi, Redocly link checker errors are not related to this PR and I'm unable to get response in slack #glcp-doc-portal channel.

it has become a common issue. Raised a couple of times, but no response. I see that several other teams also reporting a similar problem.

**Pull request merged**
